import type { GuestProfile } from "../types/guest-profile";

/**
 * Sample guest profiles for development and demo purposes.
 * In production, these would be generated by the AI Profile Engine.
 */

export const sampleGuest: GuestProfile = {
  // Identity
  id: "guest_001",
  name: "Maya Chen",
  email: "maya.chen@email.com",
  phone: "+1-415-555-0142",
  loyaltyTier: "gold",
  stayHistory: 4,

  // Raw data
  rawData: {
    socialMedia: [
      {
        platform: "instagram",
        handle: "@mayaexplores",
        bio: "Product designer ✨ Plant mom 🌿 Sunset chaser 🌅 SF → Everywhere",
        recentPosts: [
          {
            content: "Found the most incredible omakase spot in Kyoto. 12 courses, each one a tiny universe. 🍣",
            date: "2026-04-20T19:30:00Z",
            mediaType: "image",
            hashtags: ["#omakase", "#kyoto", "#foodie", "#japantravel"],
            location: "Kyoto, Japan",
            sentiment: "positive",
          },
          {
            content: "Morning yoga with this view. Nothing beats starting the day grounded. 🧘‍♀️",
            date: "2026-04-18T07:15:00Z",
            mediaType: "image",
            hashtags: ["#morningyoga", "#wellness", "#mindfulness"],
            location: "Kyoto, Japan",
            sentiment: "positive",
          },
          {
            content: "Three years of building this product and we finally launched! So grateful for this team. 🚀",
            date: "2026-03-10T16:00:00Z",
            mediaType: "image",
            hashtags: ["#startup", "#productdesign", "#launch"],
            sentiment: "positive",
          },
          {
            content: "Switched to fully plant-based this year and honestly never felt better 🌱",
            date: "2026-02-14T12:00:00Z",
            mediaType: "text",
            hashtags: ["#plantbased", "#vegan", "#health"],
            sentiment: "positive",
          },
        ],
        followers: 12400,
        interests: ["food", "travel", "yoga", "design", "wellness", "plants"],
      },
    ],
    spotify: {
      topArtists: [
        { name: "Khruangbin", genres: ["psychedelic", "funk", "world"] },
        { name: "Norah Jones", genres: ["jazz", "vocal jazz", "soul"] },
        { name: "Bonobo", genres: ["electronic", "downtempo", "ambient"] },
        { name: "Japanese Breakfast", genres: ["indie rock", "indie pop"] },
        { name: "Nujabes", genres: ["lo-fi hip hop", "jazz hop"] },
      ],
      topGenres: ["jazz", "lo-fi", "downtempo", "indie", "world music"],
      recentPlaylists: [
        {
          name: "Morning Slow",
          description: "Easy wake-up vibes",
          trackCount: 42,
          dominantGenres: ["lo-fi", "jazz"],
          dominantMood: "chill",
        },
        {
          name: "Deep Focus",
          description: "For long design sessions",
          trackCount: 67,
          dominantGenres: ["ambient", "downtempo", "electronic"],
          dominantMood: "focus",
        },
        {
          name: "Golden Hour",
          description: "Sunset drives and evening walks",
          trackCount: 35,
          dominantGenres: ["indie", "funk", "world"],
          dominantMood: "warm",
        },
      ],
      listeningMood: {
        dominantMood: "relaxed",
        energy: "low",
        valence: "uplifting",
      },
    },
    conciergeNotes: [
      {
        date: "2025-11-15T14:00:00Z",
        author: "James R.",
        category: "room_preference",
        content: "Guest requested extra firm pillows and asked for the room temperature to be set to 68°F before arrival. Prefers high floor with garden view.",
        priority: "medium",
      },
      {
        date: "2025-11-15T20:00:00Z",
        author: "Sarah L.",
        category: "dining",
        content: "Guest mentioned she is plant-based/vegan. Loved the mushroom risotto. Asked if chef could do an off-menu tasting. Very adventurous eater.",
        priority: "high",
      },
      {
        date: "2025-11-16T08:00:00Z",
        author: "James R.",
        category: "special_request",
        content: "Guest asked about morning yoga classes and if we have yoga mats available in-room. She does yoga every morning.",
        priority: "medium",
      },
      {
        date: "2025-11-16T22:00:00Z",
        author: "Sarah L.",
        category: "complaint",
        content: "Guest mentioned the lobby music was too loud during her evening tea. She values quiet, calm spaces.",
        priority: "high",
      },
      {
        date: "2025-11-17T10:00:00Z",
        author: "James R.",
        category: "compliment",
        content: "Guest loved the in-room plants. Said they made the room feel like home. Took photos for her Instagram.",
        priority: "low",
      },
      {
        date: "2026-05-01T09:00:00Z",
        author: "Concierge Desk",
        category: "occasion",
        content: "Upcoming stay coincides with guest's 30th birthday on May 18th. She mentioned it casually during booking call.",
        priority: "high",
      },
    ],
  },

  // AI-derived preferences
  preferences: {
    dining: {
      dietaryRestrictions: ["vegan", "plant-based"],
      allergies: [],
      cuisinePreferences: [
        { name: "Japanese", rank: 1, source: "social_media" },
        { name: "Mediterranean", rank: 2, source: "inferred" },
        { name: "Farm-to-table", rank: 3, source: "concierge" },
      ],
      diningStyle: "fine_dining",
      mealNotes: "Adventurous eater. Loves tasting menus and off-menu experiences. Prefers late dinners. Likely skips heavy breakfasts in favor of light, clean options.",
      beveragePreferences: ["oat milk latte", "matcha", "natural wine", "herbal tea"],
      confidence: {
        level: "high",
        basedOn: ["social_media", "concierge"],
        notes: "Vegan diet confirmed by both Instagram post (Feb 2026) and concierge dining notes.",
      },
    },
    room: {
      temperature: "cool",
      pillowType: "firm",
      bedConfiguration: "King bed, extra blanket",
      lighting: "dim",
      minibarRequests: ["sparkling water", "oat milk", "dark chocolate (vegan)", "fresh fruit"],
      bathroomPreferences: ["premium bath salts", "eucalyptus towels"],
      floorPreference: "high",
      viewPreference: "garden",
      turndownPreferences: "Lavender pillow mist, herbal tea set on nightstand",
      noisePreference: "silent",
      scent: "lavender",
      confidence: {
        level: "high",
        basedOn: ["concierge"],
        notes: "Room preferences directly stated by guest on previous stay.",
      },
    },
    ambiance: {
      musicGenres: ["jazz", "lo-fi", "downtempo", "ambient"],
      suggestedPlaylistMood: "Soft jazz or lo-fi for mornings, downtempo/ambient for evenings",
      inRoomMusicVolume: "soft",
      lobbyMusicNote: "Guest is sensitive to loud lobby music — ensure ambient levels during her tea time (typically 5-6 PM).",
      confidence: {
        level: "high",
        basedOn: ["spotify", "concierge"],
        notes: "Spotify data strongly aligns with her complaint about loud lobby music.",
      },
    },
    activities: {
      interests: [
        { name: "Yoga & Wellness", rank: 1, source: "social_media" },
        { name: "Fine Dining Experiences", rank: 2, source: "concierge" },
        { name: "Art & Design", rank: 3, source: "social_media" },
        { name: "Nature Walks", rank: 4, source: "inferred" },
        { name: "Local Culture", rank: 5, source: "social_media" },
      ],
      fitnessActivities: ["yoga", "meditation", "walking"],
      culturalInterests: ["modern art", "design exhibitions", "live jazz", "local food markets"],
      outdoorVsIndoor: "balanced",
      pacePreference: "relaxed",
      confidence: {
        level: "high",
        basedOn: ["social_media", "concierge", "spotify"],
        notes: "Consistent wellness/yoga/food theme across all data sources.",
      },
    },
    communication: {
      formality: "casual",
      preferredContactMethod: "text",
      languagePreferences: ["English"],
      personalityTraits: ["warm", "detail-oriented", "design-conscious", "values authenticity"],
      communicationNotes: "Responds well to genuine, unhurried interactions. Values experiences over material upgrades.",
      confidence: {
        level: "medium",
        basedOn: ["social_media", "concierge"],
        notes: "Personality inferred from social media tone and concierge interaction notes.",
      },
    },
  },

  // Special occasions
  specialOccasions: [
    {
      type: "birthday",
      date: "2026-05-18",
      description: "Guest's 30th birthday falls on Day 2 of her stay.",
      suggestedGestures: [
        "Vegan birthday cake from pastry chef (no fondant — she appreciates natural aesthetics)",
        "Handwritten birthday card from GM",
        "Complimentary spa treatment (yoga-focused or massage)",
        "Small potted plant as a gift (she loves plants)",
        "Curated lo-fi/jazz birthday playlist queued in room",
      ],
    },
  ],

  // Staff briefing
  staffBriefing: {
    guestName: "Maya Chen",
    stayDates: { checkIn: "2026-05-17", checkOut: "2026-05-20" },
    mustKnow: [
      { category: "Dietary", note: "Strictly vegan/plant-based. No animal products in any meal.", priority: "critical" },
      { category: "Birthday", note: "Turning 30 on May 18 (Day 2). She mentioned it casually — make it special but not over-the-top.", priority: "important" },
      { category: "Wellness", note: "Does yoga every morning. Have yoga mat in room before arrival.", priority: "important" },
      { category: "Noise", note: "Sensitive to loud music in common areas. Values calm, quiet atmosphere.", priority: "important" },
      { category: "Returning Guest", note: "4th stay, Gold loyalty. Remembers and appreciates personal touches.", priority: "info" },
    ],
    likes: [
      "In-room plants and natural decor",
      "Japanese and Mediterranean cuisine",
      "Tasting menus and off-menu chef experiences",
      "Soft jazz and lo-fi music",
      "Morning yoga and wellness activities",
      "Garden views and quiet spaces",
      "Oat milk lattes and herbal tea",
      "Authentic, unhurried experiences",
    ],
    dislikes: [
      "Loud music in lobby/common areas",
      "Heavy or overly processed food",
      "Overly formal or scripted interactions",
      "Bright room lighting",
    ],
    roomSetup: [
      "Set temperature to 68°F before arrival",
      "Extra firm pillows on bed",
      "King bed with extra blanket",
      "Place yoga mat and blocks near window",
      "Stock minibar: sparkling water, oat milk, vegan dark chocolate, fresh fruit",
      "Add 2-3 small potted plants to room",
      "Set lavender diffuser to low",
      "Queue 'Morning Slow' style playlist on room speaker (volume: low)",
      "Herbal tea set on nightstand for turndown",
      "High floor, garden view room",
    ],
    arrivalChecklist: [
      { task: "Set room to 68°F", assignedTo: "housekeeping", completed: false },
      { task: "Place firm pillows and extra blanket", assignedTo: "housekeeping", completed: false },
      { task: "Set up yoga mat and blocks", assignedTo: "housekeeping", completed: false },
      { task: "Stock vegan minibar items", assignedTo: "f_and_b", completed: false },
      { task: "Add potted plants to room", assignedTo: "housekeeping", completed: false },
      { task: "Prepare vegan welcome amenity", assignedTo: "f_and_b", completed: false },
      { task: "Brief F&B team on vegan dietary needs", assignedTo: "f_and_b", completed: false },
      { task: "Confirm birthday cake order for May 18", assignedTo: "f_and_b", completed: false },
      { task: "Prepare handwritten birthday card from GM", assignedTo: "management", completed: false },
      { task: "Queue curated playlist in room", assignedTo: "concierge", completed: false },
      { task: "Assign high-floor garden-view room", assignedTo: "front_desk", completed: false },
    ],
    alerts: [
      {
        type: "allergy",
        message: "No known allergies, but strictly vegan. Double-check ALL food items including sauces, garnishes, and minibar snacks.",
        severity: "warning",
      },
      {
        type: "complaint_history",
        message: "Previously complained about loud lobby music during evening tea (5-6 PM). Monitor ambient volume.",
        severity: "warning",
      },
      {
        type: "special_request",
        message: "Birthday on May 18 — coordinate cake, card, and spa comp. Keep it elegant and personal, not generic.",
        severity: "info",
      },
    ],
  },

  // Concierge summary (guest-facing)
  conciergeSummary: `## Welcome Back, Maya 🌿

We're delighted to have you with us again — and this time, for a very special occasion. Here's what we've prepared with you in mind:

### Your Room
Your garden-view suite on the 12th floor is ready, set to a cool 68°F with firm pillows, lavender scenting, and a yoga mat by the window for your morning practice.

### Dining
Our chef has prepared a fully plant-based menu for your stay, including a special vegan tasting experience on your birthday evening. Your minibar is stocked with oat milk, sparkling water, and artisan vegan chocolate.

### Experiences We Think You'll Love
- 🧘 **Sunrise Yoga on the Garden Terrace** — Daily at 7 AM
- 🎨 **Private Tour: Modern Art Collection at [Local Gallery]** — Curated for design lovers
- 🍽️ **Chef's Vegan Omakase** — A 7-course plant-based journey (available Thursday evening)
- 🎵 **Live Jazz at The Lounge** — Norah Jones-inspired sets, Fri & Sat 8 PM
- 🌿 **Botanical Garden Walking Tour** — Guided, Saturday morning

### Your Curated Playlist
We've set up a lo-fi jazz blend inspired by your Spotify favorites — Khruangbin, Nujabes, Norah Jones — playing softly in your room. Adjust anytime via the room tablet.

Happy early birthday, Maya. We're here to make it unforgettable. 🎂`,

  // Metadata
  profileVersion: 1,
  generatedAt: "2026-05-16T10:00:00Z",
  lastUpdated: "2026-05-16T10:00:00Z",
  dataSourcesUsed: ["social_media", "spotify", "concierge"],
  overallConfidence: {
    level: "high",
    basedOn: ["social_media", "spotify", "concierge"],
    notes: "Strong data across all three sources with high consistency. Vegan diet, wellness focus, and design aesthetic confirmed across multiple channels.",
  },
};
